name: JD

env:
  QYWX_KEY: ${{ secrets.QYWX_KEY }}
  AutoHelpOther: ${{ secrets.AutoHelpOther }}
  MARKET_COIN_TO_BEANS: ${{ secrets.MARKET_COIN_TO_BEANS }}
  FRUIT_BEAN_CARD: ${{ secrets.FRUIT_BEAN_CARD }}
  COOKIE: ${{ secrets.COOKIE }}  
  Myhealth: ${{ secrets.Myhealth }}
  MyFruit: ${{ secrets.MyFruit }}
  MyPet: ${{ secrets.MyPet }}
  MyBean: ${{ secrets.MyBean }}
  MyDreamFactory: ${{ secrets.MyDreamFactory }}
  MyJdFactory: ${{ secrets.MyJdFactory }}
  MyJdzz: ${{ secrets.MyJdzz }}
  MyJoy: ${{ secrets.MyJoy }}
  MyJxnc: ${{ secrets.MyJxnc }}
  TokenJxnc: ${{ secrets.TokenJxnc }}
  MyBookShop: ${{ secrets.MyBookShop }}
  MyCash: ${{ secrets.MyCash }}
  MySgmh: ${{ secrets.MySgmh }}
  MyCfd: ${{ secrets.MyCfd }}
  MyCity: ${{ secrets.MyCity }}
  MyZoo: ${{ secrets.MyZoo }}
  MyZooPk: ${{ secrets.MyZooPk }}
  
on:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
  schedule:
    - cron: '56 20,1,6,11,15 * * *' #UTC时间
    - cron: '56 23,4,9,14,18 * * *' #UTC时间，互补任务
  watch:
    types: started
  repository_dispatch:
    types: syj
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2 # 使用 GitHub 官方的缓存 Action。
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # 使用 package-lock.json 的 Hash 作为缓存的 key。也可以使用 package.json 代替
      - name: 'apt-get install'
        run: |
          sudo apt-get update && sudo apt-get install -y python3-pip curl vim git moreutils
          pip3 install --upgrade pip
          pip install docker-compose
      - name: '运行【docker】'
        run: |
          docker run -dit \
             -v /JD/jd/config:/jd/config \
             -v /JD/jd/log:/jd/log \
             -v /JD/jd/scripts:/jd/scripts \
             -p 5678:5678 \
             -e ENABLE_HANGUP=true \
             -e ENABLE_WEB_PANEL=true \
             --name jd \
             --hostname jd \
             --restart always \
             shuye72/jd-base:gitee


          echo PURCHASE_SHOPS="false" > config.sh
          echo AutoDelCron="true" >> config.sh
          echo AutoAddCron="true" >> config.sh
          echo RmLogDaysAgo="7" >> config.sh
          echo RandomDelay="30" >> config.sh
          echo export JXNC_NOTIFY_LEVEL="3" >> config.sh
          echo export FRUIT_BEAN_CARD=\"$FRUIT_BEAN_CARD\" >> config.sh
          echo export MARKET_COIN_TO_BEANS=\"$MARKET_COIN_TO_BEANS\" >> config.sh
          echo AutoHelpOther=\"$AutoHelpOther\" >> config.sh
          echo export QYWX_KEY=\"$QYWX_KEY\" >> config.sh
          echo export ADOLF_ADDSKU=“true” >> config.sh
          echo export ADOLF_MARTIN="true" >> config.sh

          i=1
          array=(${COOKIE//&/ })
          for var in ${array[@]}
          do
            echo Cookie$i=\"$var\" >> config.sh
            let i++
          done

          i=1
          array=(${TokenJxnc//&/ })
          for var in ${array[@]}
          do
            echo TokenJxnc$i=\'$var\' >> config.sh
            let i++
          done

          i=1
          array=(${Myhealth//&/ })
          for var in ${array[@]}
          do
            echo Myhealth$i=\"$var\" >> config.sh
            let i++
          done
          i=1


          i=1
          array=(${MyFruit//&/ })
          for var in ${array[@]}
          do
            echo MyFruit$i=\"$var\" >> config.sh
            let i++
          done

          i=1
          array=(${MyPet//&/ })
          for var in ${array[@]}
          do
            echo MyPet$i=\"$var\" >> config.sh
            let i++
          done


          i=1
          array=(${MyBean//&/ })
          for var in ${array[@]}
          do
            echo MyBean$i=\"$var\" >> config.sh
            let i++
          done

          i=1
          array=(${MyDreamFactory//&/ })
          for var in ${array[@]}
          do
            echo MyDreamFactory$i=\"$var\" >> config.sh
            let i++
          done

          i=1
          array=(${MyJdFactory//&/ })
          for var in ${array[@]}
          do
            echo MyJdFactory$i=\"$var\" >> config.sh
            let i++
          done

          i=1
          array=(${MyJdzz//&/ })
          for var in ${array[@]}
          do
            echo MyJdzz$i=\"$var\" >> config.sh
            let i++
          done

          i=1
          array=(${MyJoy//&/ })
          for var in ${array[@]}
          do
            echo MyJoy$i=\"$var\" >> config.sh
            let i++
          done


          i=1
          array=(${MyJxnc//&/ })
          for var in ${array[@]}
          do
            echo MyJxnc$i=\'$var\' >> config.sh
            let i++
          done


          i=1
          array=(${MyBookShop//&/ })
          for var in ${array[@]}
          do
            echo MyBookShop$i=\"$var\" >> config.sh
            let i++
          done

          i=1
          array=(${MyCash//&/ })
          for var in ${array[@]}
          do
            echo MyCash$i=\"$var\" >> config.sh
            let i++
          done


          i=1
          array=(${MySgmh//&/ })
          for var in ${array[@]}
          do
            echo MySgmh$i=\"$var\" >> config.sh
            let i++
          done

          i=1
          array=(${MyCfd//&/ })
          for var in ${array[@]}
          do
            echo MyCfd$i=\"$var\" >> config.sh
            let i++
          done


          i=1
          array=(${MyCity//&/ })
          for var in ${array[@]}
          do
            echo MyCity$i=\"$var\" >> config.sh
            let i++
          done

          
          i=1
          array=(${MyZoo//&/ })
          for var in ${array[@]}
          do
            echo MyZoo$i=\"$var\" >> config.sh
            let i++
          done


          i=1
          array=(${MyZooPk//&/ })
          for var in ${array[@]}
          do
            echo MyZooPk$i=\"$var\" >> config.sh
            let i++
          done
          
          docker exec jd bash git_pull
          echo "Waiting for 5 seconds..."
          sleep 5
          docker exec jd /bin/sh -c 'mv /jd/config/config.sh /jd/config/config.sh.bak'
          docker cp ./config.sh jd:/jd/config/config.sh

          #echo "Waiting for 60 seconds..."
          #sleep 60
          docker cp ./jd/ jd:/
          #docker exec jd bash monkcoder.sh >/dev/null 2>&1
          docker exec jd /bin/sh -c "cp -r ./diy/. ./scripts/"
          #docker exec jd /bin/sh -c "rm ./scripts/monkcoder_z_city_cash.js"
          #docker exec jd /bin/sh -c "echo -e '1 0-23/4 * 5,6 * bash jd monkcoder_z_city_cash.js' >> /etc/crontabs/root"

      - name: SSH connection to Actions @ Ctrl+C to enter, Ctrl+D to exit
        uses: P3TERX/ssh2actions@main
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
      - name:  '运行【倒计时】'
        run: |
          sleep 18000
